# Generated by Django 5.0.1 on 2024-02-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comiqueriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='distribuidor',
            options={'ordering': ['nombre'], 'verbose_name': 'Distribuidor', 'verbose_name_plural': 'Distribuidores'},
        ),
    ]
